### ISSUE TITLE
Token not being used?

### ISSUE THREAD

**Issue by ronnyandre** [lostfields/python-panasonic-comfort-cloud#22]
What is the deal with saving the token and the token parameter, if I always have to provide username and password?

**Comment by lostfields** [comment]
it's making it faster, if it has a token it's using that instead of your username and password, but if the token is expired or missing it has to authenticate again. If we are going to authenticate for each request it will be a lot slower.

I wish we didn't need to provide the username and password all the time, but panasonic doesn't have OAuth

**Comment by ronnyandre** [comment]
I see now that it's only the direct commands to the script that requires u/p every time..

Do you know the expiration of the token?

**Comment by lostfields** [comment]
It's as long as your app remembers you, and the panasonic app seems to forget you every 14 days? or is it a month?
