### ISSUE TITLE
Merge?

### ISSUE THREAD

**Issue by thxraph** [lostfields/python-panasonic-comfort-cloud#98]
Hello!

Is a merge of the requests is gonna happen? What is the correct way to get this working again? should I use a fork from another user?

thank you,
Raphael

**Comment by mcbrain78** [comment]
Hi Raphael,

I am using [PR94](https://github.com/lostfields/python-panasonic-comfort-cloud/pull/94) in the meantime. It works well!

-Markus

**Comment by helicalchris** [comment]
it would be useful if PR94 was merged as until the new release hits pypi it doesn't get pulled into the Home Assistant integration

**Comment by lostfields** [comment]
I'll look into it, one concern about #94 is that it isn't only introducing new auth, but it's a complete rewrite.

**Comment by thxraph** [comment]
> I'll look into it, one concern about #94 is that it isn't only introducing new auth, but it's a complete rewrite.

if it works.... because right now it doesn't.

Thank you guys for the info, I merged the changes manually and everything is working again after 2 little changes to my code for the auth. I have 2 scripts using the API to control the AC units via mqtt for nodered integration. 1 to make changes, 1 to pull the changes (read/write). 

Thank you :)

**Comment by LudovicRousseau** [comment]
I agree with @lostfields here. The PR is not just adding support of the new auth but also unrelated code and API changes.

It was easy to adapt my code to the new API. see https://github.com/LudovicRousseau/python-panasonic-comfort-cloud/commit/b2989c6eed86c94d17908ddf791f97698f4331d0

But I think we can have the new auth support without breaking the API.

**Comment by thxraph** [comment]
Well, it makes sense, you don't want to break back compatibility.
I'll leave you pros to it. I don't know what is the extend of the modification, maybe a simple wrapper would do to keep backcompat but on the other hand that is how, slowly and over time, codebases become clusterf*#ks.
Given the amount of code built over this codebase, it would be great to get a new version that works... and could be simply pip updated.
I'm just a little hobby code thinkerer with an mqtt caller interfaced on it, and everything works again for me.
I'm also very grateful to @lostfields for this code given the terrible support from Panasonic... my next ACs will be Mitsubishi or Samsung as the support is much better there. I might end up converting the panas to ESP local mqtt and bypass the cloud completely.
Anyway, I diverge, many thanks to everybody involved, you guys are stars!
Raphael

**Comment by helicalchris** [comment]
Hi all so this being as it is, and I appreciate that the PR has its issues, is there a way forward for this project long term?  I ask because the Home Assistant integration (and I assume lots of others) are using this, so we are all a bit stuck right now.  I also appreciate chasing without helping isn’t particular helpful but believe me keeping me away from the code is best for everyone!

**Comment by lostfields** [comment]
If the author of PR #94 allows it, I can refactor it to make it less a rewrite but still keep the good stuff (more or less keep it backwards compatible). Don't know why that isn't done in the beginning @helicalchris

**Comment by lostfields** [comment]
I'm making a few changes in #100

**Comment by lostfields** [comment]
@thxraph @mcbrain78 @LudovicRousseau 
Do you mind testing #100 and see if that works similar to #94 ? There is a few changes how the code is lay out.

**Comment by mcbrain78** [comment]
I‘m traveling unfortunately, and don’t have access to the AC for a while

**Comment by thxraph** [comment]
Hi, traveling too, i should be able to try end of next week.

**Comment by LudovicRousseau** [comment]
I use `upstream/feature/oauth2` and modified my code to use #100 API. **It works fine for me.**

You should update `README.md` now that the method `pcomfortcloud.Session()` requires a token parameter.

# Invalid refresh token.

I don't know if it useful or not. With the code from #99 and since this morning I get the error:
```
pcomfortcloud.exceptions.ResponseError: (refresh_token: Expected status code 200, received: 403: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
```
The quick fix is to remove the `token.json` file and a new one is recreated. Maybe my refresh token has expired?

It would be fine if this case could be handled automatically and internally by `pcomfortcloud`
If `pcomfortcloud` receives "Unknown or invalid refresh token." just ignore the token and generate a new one. Maybe do it only once to avoid a possible infinite loop.

# Token expires
When I get the error:
```
pcomfortcloud.exceptions.ResponseError: (get_groups: Expected status code 200, received: 401: {"code":"4100", "message": "Token expires"}
```
I have nothing to do and the token will be refreshed the next time.
It would also be fine if this coule be handled automatically but that is less critical as above.

**Comment by danielcherubini** [comment]
@lostfields you just need to check for any 4XX, then refresh your token. So any API call results in an unauthorised, that's it's way of saying your access token has expired, please refresh. calling login on every single call will result in them trying to ban us again possibly

**Comment by lostfields** [comment]
> @lostfields you just need to check for any 4XX, then refresh your token. So any API call results in an unauthorised, that's it's way of saying your access token has expired, please refresh. calling login on every single call will result in them trying to ban us again possibly

Yeah, I know. We have to check for that when using refresh token, but that doesn't solve the expire check, the login method does that, and only authenticate if it's expired - that avoids flooding panasonic
